package:
  name: nfpm
  version: "2.43.0"
  epoch: 0
  description: nFPM is a simple, 0-dependencies, deb, rpm, apk and arch linux packager written in Go
  copyright:
    - license: MIT
environment:
  contents:
    packages:
      - git
      - go
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/goreleaser/nfpm
      tag: v${{package.version}}
      expected-commit: 2e47af64a3f33d32ec1395dbd56165c4feb2bc21
  - uses: go/build
    with:
      packages: ./cmd/nfpm
      modroot: .
      output: nfpm
      ldflags: -X main.version=v${{package.version}}
update:
  enabled: true
  github:
    identifier: goreleaser/nfpm
    strip-prefix: v
test:
  environment:
    contents:
      packages:
        - ca-certificates-bundle
  pipeline:
    - name: version check
      runs: |
        nfpm --version
        nfpm --help
